<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPbT2oho\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPbT2oho/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPbT2oho.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPbT2oho\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPbT2oho\App_KernelDevDebugContainer([
    'container.build_hash' => 'PbT2oho',
    'container.build_id' => '099ff26e',
    'container.build_time' => 1714807092,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPbT2oho');
