<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvFDqVj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvFDqVj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFvFDqVj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFvFDqVj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFvFDqVj\App_KernelDevDebugContainer([
    'container.build_hash' => 'FvFDqVj',
    'container.build_id' => 'd36a9122',
    'container.build_time' => 1715670151,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvFDqVj');
