<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfEDld1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfEDld1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfEDld1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfEDld1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfEDld1\App_KernelDevDebugContainer([
    'container.build_hash' => 'XfEDld1',
    'container.build_id' => 'b905b4d9',
    'container.build_time' => 1714802506,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfEDld1');
